### ISSUE TITLE
AssertionError: IFMAP and Filter demands out of sync in systolic_compute_ws.py with GEMM inputs

### ISSUE THREAD

**Issue by dkadiyal** [scalesim-project/scale-sim-v2#59]
Scalesim fails to run the default _test_mnk_input.csv_ from the repo using WS method in GEMM mode. The code asserts with the following error log as shown below:

```
====================================================
Array Size:     256x256
SRAM IFMAP (kB):        6144
SRAM Filter (kB):       6144
SRAM OFMAP (kB):        2048
Dataflow:       Weight Stationary
CSV file path:  topologies/GEMM_mnk/test_mnk_input.csv
Number of Remote Memory Banks:  1
Working in ESTIMATE BANDWIDTH mode.

====================================================
Running Layer 0
(1149, 256)   (894, 256)
Traceback (most recent call last):
  File "/nethome/dkadiyala3/git_repos/scale-sim-v2/scalesim/scale.py", line 39, in <module>
    s.run_scale(top_path=logpath)
  File "/nethome/dkadiyala3/venv_py3.9/lib/python3.9/site-packages/scalesim-2.0.1-py3.9.egg/scalesim/scale_sim.py", line 86, in run_scale
    self.run_once()
  File "/nethome/dkadiyala3/venv_py3.9/lib/python3.9/site-packages/scalesim-2.0.1-py3.9.egg/scalesim/scale_sim.py", line 105, in run_once
    self.runner.run()
  File "/nethome/dkadiyala3/venv_py3.9/lib/python3.9/site-packages/scalesim-2.0.1-py3.9.egg/scalesim/simulator.py", line 79, in run
    single_layer_obj.run()
  File "/nethome/dkadiyala3/venv_py3.9/lib/python3.9/site-packages/scalesim-2.0.1-py3.9.egg/scalesim/single_layer_sim.py", line 126, in run
    ifmap_demand_mat, filter_demand_mat, ofmap_demand_mat = self.compute_system.get_demand_matrices()
  File "/nethome/dkadiyala3/venv_py3.9/lib/python3.9/site-packages/scalesim-2.0.1-py3.9.egg/scalesim/compute/systolic_compute_ws.py", line 361, in get_demand_matrices
  File "/nethome/dkadiyala3/venv_py3.9/lib/python3.9/site-packages/scalesim-2.0.1-py3.9.egg/scalesim/compute/systolic_compute_ws.py", line 174, in create_demand_matrices
**AssertionError: IFMAP and Filter demands out of sync**
```

========================================
**Steps to reproduce this issue.**
1. Install scalesim following the steps mentioned in the README
2. then run scalesim using the following command:
`python3 scalesim/scale.py -c configs/google.cfg -t topologies/GEMM_mnk/test_mnk_input.csv -i gemm`

**===================== ROOT CAUSE OF ISSUE ==========================**

This happens due to a incorrect generation of demand_matrices in function `def create_ifmap_demand_mat(self)`: in _systolic_compute_ws.py_. 
The following lines in the code are redundant along with the previous transformations on _`this_fold_matrix`_.
               
```
                # Add skew to the IFMAP demand matrix to reflect systolic pipeline fill
                this_fold_demand = skew_matrix(this_fold_demand)
```

**===================== POSSIBLE FIXES =======================**
**Method:1: To comment out the above mentioned line and that should fix that issue.** 

Let's say Sr (K-dim) = 256, Sc (N-dim) = 64, and T (m-dim) = 128. 
Our IFMAP is (T x Sr) =128 x 256 and our Filter is (Sr x Sc) = 256 x 64. 
Let's consider our systolic array as 256 x 256.

In this case, let's consider the following matrices
```
A =  transpose(IFMAP) = (Sr X T) = 256 x 128,
B =  to get the last elem of IFMAP to just reach the beginning of Systolic array = ( Sr, (T + arr_row-1)) = (256, (128+255)) = (256, 383) 
C = for the last elem of IFMAP to traverse the systolic array from beginning to right-most end = (Sr, (T + arr_row-1 + arr_col-1)) = (256, 638)
D  =  to pre-fill the weights into the systolic array = (Sr, (T + arr_row-1 + arr_col-1 + arr_row)) = (256 x 894)

```
Therefore the final demand matrix is trans(D) = (894, 256) which matches the same for Filter-matrix (894,256).

However, it is **not** the right way to do so since we need the _skew generation_ to replicate the actual dataflow into systolic array. Hence, the below method resolves it properly:

**Method-2:** 
**Keeping the _skew_matrix_ transformation, since it make more sense.**

```
A. skew_matrix(IFMAP) -> (T+arr_row-1, Sr) = (128+255,256)
B. Add cycles to traverse the systolic array = concat(A, (arr_col-1, Sr)) = (383+255, 256) = (638, 256)
C. Finally add the cycles to fill the weights in = concat(B, (arr_row, Sr)) = (638+256, 256) = (894, 256)
```

Fix in the code:

```
def create_ifmap_demand_mat(self):
        assert self.params_set_flag, 'Parameters are not set'

        inter_fold_gap_prefix = self.arr_row
        inter_fold_gap_prefix_mat = np.ones((inter_fold_gap_prefix, self.arr_row)) * -1

        #inter_fold_gap_suffix = self.arr_row + self.arr_col - 2
        inter_fold_gap_suffix = self.arr_col - 1
        #The last input need self.arr_col - 1 cycles to reduce along the last column.

        inter_fold_gap_suffix_mat = np.ones((inter_fold_gap_suffix, self.arr_row)) * -1

        for fc in range(self.col_fold):
            for fr in range(self.row_fold):
                col_start_id = fr * self.arr_row
                col_end_idx = min(col_start_id + self.arr_row, self.Sr)
                delta = self.arr_row - (col_end_idx - col_start_id)

                # Indexing the cols with row start and row end idx are correct
                # See the comment on ifmap_prefetch generation
                this_fold_demand = self.ifmap_op_mat[:,col_start_id: col_end_idx]
                self.ifmap_reads += this_fold_demand.shape[0] * this_fold_demand.shape[1]
                
                # Take into account under utilization
                if delta > 0:
                    null_req_mat = np.ones((self.T, delta)) * -1
                    this_fold_demand = np.concatenate((this_fold_demand, null_req_mat), axis=1)

                # Add skew to the IFMAP demand matrix to reflect systolic pipeline fill
                this_fold_demand = skew_matrix(this_fold_demand)

                # Account for the cycles for input to traverse systolic array
                this_fold_demand = np.concatenate((this_fold_demand, inter_fold_gap_suffix_mat), axis=0)

                # Account for the cycles for weights to load
                this_fold_demand = np.concatenate((inter_fold_gap_prefix_mat, this_fold_demand), axis=0)

                if fr == 0 and fc == 0:
                    self.ifmap_demand_matrix = this_fold_demand
                else:
                    self.ifmap_demand_matrix = np.concatenate((self.ifmap_demand_matrix, this_fold_demand), axis=0)
```

This code works and I have tested on multiple cases. (Tested on inputs that are bigger, smaller, and equal to the size of systolic array.

I request the repo owners to please review my issue. If the proposed fix is good,  then I will formally send a pull request with the fixed code along with the unit testcases. Thank you.

Regards,
Divya Kiran K.
dkadiyala3@gatech.edu

**Comment by DrSpace** [comment]
I've just came accross this issue too. Thank you for sharing.

**Comment by Z-KN** [comment]
Same issue. Simply run `python3 scalesim/scale.py -c configs/eyeriss.cfg -t topologies/conv_nets/test.csv` can fail.

**Comment by ritikraj7** [comment]
Hi @dkadiyal, thank you for pointing out this bug. I really appreciate the efforts you put in to solve this issue but the fix is different from what you suggested. Please refer to PR #63, which correctly solves the issue.
